"""empty message

Revision ID: b810d4c7f8e8
Revises: 
Create Date: 2024-01-12 13:04:43.962012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b810d4c7f8e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apartment')
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('square',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               nullable=False)
        batch_op.alter_column('ward',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('district',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('district',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ward',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('square',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('apartment',
    sa.Column('field1', sa.INTEGER(), nullable=True),
    sa.Column('Unnamed:0', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('date_post', sa.TEXT(), nullable=True),
    sa.Column('exp_post', sa.TEXT(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('square', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('contact_name', sa.TEXT(), nullable=True),
    sa.Column('contact_phone', sa.TEXT(), nullable=True),
    sa.Column('direction', sa.TEXT(), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('img_url_src', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('street', sa.INTEGER(), nullable=True),
    sa.Column('ward', sa.TEXT(), nullable=True),
    sa.Column('district', sa.TEXT(), nullable=True),
    sa.Column('province', sa.TEXT(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True)
    )
    op.drop_table('cart_item')
    # ### end Alembic commands ###
