version: '3'
services:
  real-estate-serivce:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
